### ISSUE TITLE
'NSInvalidArgumentException', reason: 'Unacceptable type of value for attribute: property = "thirdOrFourthDegree"

### ISSUE THREAD

**Issue by johndpope** [eNorthug/Harmonix#1]
Hi Even,

This is quite a body of work you have put together on music theory. I super keen to get app up and playing with it. I'm trying to harmonise some notes - and I think I can salvage some of your code. 

I tried building your app - but it blows up with this error. 
Is this a core data 'feature'? It appears to be rigged up fine. 
So maybe it's corrupted. 

![screen shot 2015-02-06 at 2 32 40 pm](https://cloud.githubusercontent.com/assets/289994/6074184/1332807a-ae0d-11e4-8aba-def7fcde7acf.png)

2015-02-06 14:23:50.913 Harmonix[45295:3381971] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unacceptable type of value for attribute: property = "thirdOrFourthDegree"; desired type = NSString; given type = **NSArrayI; value = (
    1,
    3,
    5,
    7
).'
**\* First throw call stack:
(
    0   CoreFoundation                      0x0000000107e9ff35 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x0000000106b39bb7 objc_exception_throw + 45
    2   CoreData                            0x00000001067f4aa3 _PFManagedObject_coerceValueForKeyWithDescription + 3203
    3   CoreData                            0x00000001067cdb51 _sharedIMPL_setvfk_core + 177
    4   Harmonix                            0x0000000104d365df -[AppDelegate addObjects] + 12207
    5   Harmonix                            0x0000000104d32d32 -[AppDelegate application:didFinishLaunchingWithOptions:] + 114
    6   UIKit                               0x0000000104df1475 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 234
    7   UIKit                               0x0000000104df1fbc -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2463
    8   UIKit                               0x0000000104df4d2c -[UIApplication _runWithMainScene:transitionContext:completion:] + 1350
    9   UIKit                               0x0000000104df3bf2 -[UIApplication workspaceDidEndTransaction:] + 179
    10  FrontBoardServices                  0x0000000106ee02a3 __31-[FBSSerialQueue performAsync:]_block_invoke + 16
    11  CoreFoundation                      0x0000000107dd553c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK** + 12
    12  CoreFoundation                      0x0000000107dcb285 __CFRunLoopDoBlocks + 341
    13  CoreFoundation                      0x0000000107dcb045 __CFRunLoopRun + 2389
    14  CoreFoundation                      0x0000000107dca486 CFRunLoopRunSpecific + 470
    15  UIKit                               0x0000000104df3669 -[UIApplication _run] + 413
    16  UIKit                               0x0000000104df6420 UIApplicationMain + 1282
    17  Harmonix                            0x0000000104d32c13 main + 115
    18  libdyld.dylib                       0x000000010bcd5145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by johndpope** [comment]
@eNorthug thanks for your efforts on this project. 
I'm doing some spring cleaning and closing out my old github issues tickets.
152 to go.

**Comment by eNorthug** [comment]
John
Please excuse me. I'm a GitHub amateur. Didn't see you're answer before today, more than two years later. Harmonic was some unfinished material, 4-5 years back. Now, I'm working on a music app dealing with piano playing and notation. Interesting?
Even

**Comment by johndpope** [comment]
Hi Even,
that sounds great. 
are you rolling swift or objective-c 
you maybe interested in this project
https://github.com/johndpope/KZPMusicNotation
there's another noteworthy one in github / pays to dig around.

JP

**Comment by eNorthug** [comment]
Hello again
I had a look at your notation plug-in. A note and staff midi-viewer. Sure
makes things easier for developers wanting to visualize midi by notation.
I'm writing music app code myself. Chord sequencing for keyboards, with a
radical new notation system, emphasising harmonics before metrics, contrary
to the prevailing system.
Like to build som more music stuff?
Even

**Comment by johndpope** [comment]
got a baby due any week. 
I have a desktop app - http://Komposer.io was thinking of rebooting it with tensorflow + machine learning.

sound like you're re-inventing the wheel. not judging - I personally like the circle scales.
https://www.google.com/search?q=circle+scale+music&safe=off&rlz=1C5CHFA_enUS734US734&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi45rGi7ujTAhWBSCYKHYO7DW8Q_AUICigB&biw=1004&bih=543


can't you salvage some existing code?

just search for
'pod music'

-> MusicalScaleKit (0.2.0)
   Generate notes on Musical Scale
   pod 'MusicalScaleKit', '~> 0.2.0'
   - Homepage: https://github.com/muukii/MusicalScaleKit
   - Source:   https://github.com/muukii/MusicalScaleKit.git
   - Versions: 0.2.0, 0.1.0 [master repo]

-> MusicKit (0.2.0)
   Swift music framework
   pod 'MusicKit', '~> 0.2.0'
   - Homepage: https://github.com/benzguo/MusicKit
   - Source:   https://github.com/benzguo/MusicKit.git
   - Versions: 0.2.0, 0.1.1, 0.1.0 [master repo]

-> MusicMojoLyrica (1.0.0)
   Library to search music from Itunes
   pod 'MusicMojoLyrica', '~> 1.0.0'
   - Homepage: https://github.com/rajeshvardev/ItunesMusicSearch
   - Source:   https://github.com/rajeshvardev/ItunesMusicSearch.git
   - Versions: 1.0.0 [master repo]

-> MusicTheory (1.0.6)
   A music theory library for Swift OS X and iOS apps
   pod 'MusicTheory', '~> 1.0.6'
   - Homepage: https://github.com/danielbreves/MusicTheory
   - Source:   https://github.com/danielbreves/MusicTheory.git
   - Versions: 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 0.4.2, 0.4.1, 0.3.0, 0.2.0, 0.0.1 [master repo]

  pod 'MusicTheorySwift', '~> 0.0.4'
   - Homepage: https://github.com/cemolcay/MusicTheory
   - Source:   https://github.com/cemolcay/MusicTheory.git
   - Versions: 0.0.4, 0.0.3, 0.0.2 [master repo]

-> GVMusicPlayerController (0.5.0)
   The power of AVPlayer with the simplicity of MPMusicPlayerController.
   pod 'GVMusicPlayerController', '~> 0.5.0'
   - Homepage: https://github.com/gangverk/GVMusicPlayerController
   - Source:   https://github.com/gangverk/GVMusicPlayerController.git
   - Versions: 0.5.0, 0.4.0, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.0, 0.1.0 [master repo]

-> NCMusicEngine (0.1.5)
   A simple and easy-to-use music engine support playing-while-downloading feature.
   pod 'NCMusicEngine', '~> 0.1.5'
   - Homepage: https://github.com/nickcheng/NCMusicEngine
   - Source:   https://github.com/nickcheng/NCMusicEngine.git
   - Versions: 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.0 [master repo]

-> ZLMusicFlowWaveView (0.0.1)
   A ZLSinusWaveView subclass inspired by 乐流/MusicFlow
   pod 'ZLMusicFlowWaveView', '~> 0.0.1'
   - Homepage: https://github.com/zhxnlai/ZLMusicFlowWaveView
   - Source:   https://github.com/zhxnlai/ZLMusicFlowWaveView.git
   - Versions: 0.0.1 [master repo]

-> ESTMusicIndicator (0.1.3)
   Cool Animated music indicator view written in Swift.
   pod 'ESTMusicIndicator', '~> 0.1.3'
   - Homepage: https://github.com/Aufree/ESTMusicIndicator

-> BeamMusicPlayerViewController (0.2.1)
   An iPhone/iPad view controller to visualize and control music playback.
   pod 'BeamMusicPlayerViewController', '~> 0.2.1'
   - Homepage: https://github.com/BeamApp/MusicPlayerViewController
   - Source:   https://github.com/BeamApp/MusicPlayerViewController.git
   - Versions: 0.2.1, 0.2.0, 0.1.0 [master repo]
   - Subspecs:
     - BeamMusicPlayerViewController/MediaPlayer (0.2.1)

-> GoogleMusicClient (1.0)
   Google Music client
   pod 'GoogleMusicClient', '~> 1.0'
   - Homepage: https://github.com/elliotchance/GoogleMusicClient
   - Source:   https://github.com/elliotchance/GoogleMusicClient.git
   - Versions: 1.0 [master repo]

-> ConnectMusics (1.0.0)
   ConnectMusics is a framework which allow you to simply connect multiple music provider like Spotify and AppleMusic
   pod 'ConnectMusics', '~> 1.0.0'
   - Homepage: https://github.com/shemana/ConnectMusics
   - Source:   https://github.com/shemana/ConnectMusics.git
   - Versions: 1.0.0, 0.35.2, 0.35.0, 0.30.2, 0.20.1 [master repo]

-> EECircularMusicPlayerControl (0.2.1)
   A control to play a music with a progress indicator.
   pod 'EECircularMusicPlayerControl', '~> 0.2.1'
   - Homepage: https://github.com/el-eleven/EECircularMusicPlayerControl

**Comment by eNorthug** [comment]
Hi, John

Wow. That was a load. Your Komposer does much of what I had in mind,
notationally and functionally.  Good work, and even better thinking :)

I should have been more precise. I'm an amateur. Learned Objective-C by
myself, and some Swift. The links and their examples make me think. There
is a lot of developer skills out there, and music interest. But are these
libraries really being put to work? Perhaps this role is more like driving
an evolution, where one project springs from another, occasionally
triggering commercialisation and revenue. I never quite understood github,
except for the sharing and collaboration part. But I guess there are plenty
of articles on github and business.

I hope I'm not re-inventing the wheel :) That would have been a life
wasted. Here's the story:

I play the piano and read music theory.  I'm a classical pianist, drawn
towards improvisation and composing. That means fat chords and smooth
progressions, and a lot more. So I'm modelling Tonality, where harmonic and
also metric structures are basic. It's more about maths than algorithms, in
a way.
The vertical piano roll connects to the piano keyboard. You do directly
what Synthesis does by MIDI import. Therefore, your approach hits me as a
performer. I'm going further though, labelling the pitches (pc, note,
interval, finger etc), showing triads and melodic lines. The model works
both ways, detecting and sequencing the structures we all know, within the
restraints of tonality, making it ...... music.
Congrats with the baby. I just saw my own three kids leave the nest.
You'll surely be busy. I'll applying for incubator facilities shortly, with
the guys behind the Opera browser. I need other people for a universe of
ideas become reality.
Best of luck. And please let me know if you want to make further efforts
into tonality.
Even
